![image.png](https://cdn.nlark.com/yuque/0/2021/png/2923644/1616981737661-3fda5176-505c-4c3d-becb-8618d9407f04.png#averageHue=%23302b2a&height=100&id=HJd4w&originHeight=199&originWidth=1023&originalType=binary&ratio=1&rotation=0&showTitle=false&size=31936&status=done&style=none&title=&width=511.5)<br />此时service为null     但是一个内里面的其他方法却注入成功。<br />找了一下午也没找到。后面看到切面图标<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/2923644/1616981810482-044a9b31-80e9-475b-af5b-28180c8834ef.png#averageHue=%23556638&height=373&id=VJHjS&originHeight=745&originWidth=256&originalType=binary&ratio=1&rotation=0&showTitle=false&size=34431&status=done&style=none&title=&width=128)<br />发现不一样，然后仔细一看，发现修饰符用错了。但是会出现这样的情况，也很奇怪<br />在某些时候就算方法修饰符为private时，注入的service依然是有值的，但是后面又是null了
